# SD212: Graph Learning

# Check your skills in Python & numpy


This notebook presents some basic data structures of Python and some operations on numpy arrays.


Recall that you can use:

- `tab` for completion
- ? for inline help
- ?? for inline code (when available)


In [79]:
# inline help
sorted?

Signature: sorted(iterable, /, *, key=None, reverse=False)
Docstring:
Return a new list containing all items from the iterable in ascending order.

A custom key function can be supplied to customize the sort order, and the
reverse flag can be set to request the result in descending order.
Type:      builtin_function_or_method

In [80]:
# your code
def add(x, y):
    """Add two numbers."""
    return x + y

In [81]:
add?

Signature: add(x, y)
Docstring: Add two numbers.
File:      c:\users\gabriele\appdata\local\temp\ipykernel_23964\1506788103.py
Type:      function

In [82]:
add??

Signature: add(x, y)
Source:   
def add(x, y):
    '''Add two numbers.'''
    return x + y
File:      c:\users\gabriele\appdata\local\temp\ipykernel_23964\1506788103.py
Type:      function

## List


In [83]:
names = ["Alice", "Bernard", "Carole", "David"]

In [84]:
names[:2]

['Alice', 'Bernard']

In [85]:
names[-2:]

['Carole', 'David']

In [86]:
names.append("Elodie")

In [87]:
names += ["Ferdinand", "Gabrielle"]

In [88]:
names

['Alice', 'Bernard', 'Carole', 'David', 'Elodie', 'Ferdinand', 'Gabrielle']

In [89]:
names_sublist = [name for name in names if "i" not in name]

In [90]:
names_sublist

['Bernard', 'Carole']

## Set


In [91]:
set(names)

{'Alice', 'Bernard', 'Carole', 'David', 'Elodie', 'Ferdinand', 'Gabrielle'}

In [92]:
set(names_sublist) <= set(names)

True

In [93]:
set(names) - set(names_sublist)

{'Alice', 'David', 'Elodie', 'Ferdinand', 'Gabrielle'}

In [94]:
names += ["Alice"]

In [95]:
names

['Alice',
 'Bernard',
 'Carole',
 'David',
 'Elodie',
 'Ferdinand',
 'Gabrielle',
 'Alice']

In [96]:
len(names)

8

In [97]:
len(set(names))

7

In [98]:
a = set(names)

In [99]:
b = {"Hector", "Irina"}

In [100]:
a & b

set()

In [101]:
a | b

{'Alice',
 'Bernard',
 'Carole',
 'David',
 'Elodie',
 'Ferdinand',
 'Gabrielle',
 'Hector',
 'Irina'}

In [102]:
b.add("Alice")

In [103]:
a & b

{'Alice'}

## Dictionary


In [104]:
len(names)

8

In [105]:
length = {name: len(name) for name in names}

In [106]:
len(length)

7

In [107]:
list(length.keys())

['Alice', 'Bernard', 'Carole', 'David', 'Elodie', 'Ferdinand', 'Gabrielle']

In [108]:
list(length.values())

[5, 7, 6, 5, 6, 9, 9]

In [109]:
for name in length:
    print(name, length[name])

Alice 5
Bernard 7
Carole 6
David 5
Elodie 6
Ferdinand 9
Gabrielle 9


In [110]:
length_to_add = {name: len(name) for name in b}

In [111]:
length.update(length_to_add)

In [112]:
for name in length:
    print(name, length[name])

Alice 5
Bernard 7
Carole 6
David 5
Elodie 6
Ferdinand 9
Gabrielle 9
Hector 6
Irina 5


## Numpy


In [113]:
import numpy as np

In [114]:
x = np.array([5, 1, 2, 4])

In [115]:
y = np.zeros(5)

In [116]:
z = np.zeros_like(x, dtype=int)

In [117]:
x[:2]

array([5, 1])

In [118]:
x[-2:]

array([2, 4])

In [119]:
np.sort(x)

array([1, 2, 4, 5])

In [120]:
np.argsort(x)

array([1, 2, 3, 0], dtype=int64)

In [121]:
np.argsort(-x)

array([0, 3, 2, 1], dtype=int64)

In [122]:
A = np.arange(12).reshape(3, -1)

In [123]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
A.shape

(3, 4)

In [125]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [126]:
A.sum(axis=0)

array([12, 15, 18, 21])

In [127]:
A.sum(axis=1)

array([ 6, 22, 38])

In [128]:
A.dot(x)

array([ 17,  65, 113])

In [129]:
A[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [130]:
A[:2, 1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [131]:
a = np.arange(4)
b = np.arange(5)
np.outer(a, b)

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [132]:
index = np.array([0, 1, 1, 2, 0])

In [133]:
x[index]

array([5, 1, 1, 2, 5])

In [134]:
np.unique(x[index])

array([1, 2, 5])

In [135]:
np.unique(x[index], return_counts=True)

(array([1, 2, 5]), array([2, 1, 2], dtype=int64))

In [136]:
x = np.arange(-3, 10)

In [137]:
x > 0

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [138]:
np.sum(x > 0)

9

In [139]:
x[x > 0]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
np.nonzero(x)

(array([ 0,  1,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64),)

In [141]:
np.flatnonzero(x > 0)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64)

In [142]:
A = np.random.randint(5, size=(5, 7))

In [143]:
A > 1

array([[ True,  True, False,  True,  True, False,  True],
       [False,  True,  True,  True,  True,  True, False],
       [ True, False, False, False, False, False,  True],
       [ True, False, False,  True,  True,  True,  True],
       [False,  True, False, False,  True,  True, False]])

In [144]:
A[A > 1]

array([3, 3, 3, 3, 2, 2, 3, 2, 2, 2, 2, 2, 2, 3, 3, 2, 4, 2, 4, 4])

In [145]:
np.nonzero(A)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
        3, 3, 4, 4, 4, 4], dtype=int64),
 array([0, 1, 3, 4, 6, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 0, 1, 3, 4,
        5, 6, 0, 1, 4, 5], dtype=int64))

In [146]:
A[A.nonzero()]

array([3, 3, 3, 3, 2, 1, 2, 3, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 1, 3, 3,
       2, 4, 1, 2, 4, 4])

In [147]:
np.repeat(np.arange(5), 4)

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [148]:
# max per slice
np.maximum.reduceat(np.arange(10), [0, 3, 7])

array([2, 6, 9])

In [149]:
# add per slice
np.add.reduceat(np.arange(10), [0, 3, 7])

array([ 3, 18, 24])

In [150]:
np.random.choice(6)

4

In [151]:
np.random.choice([1, 3, 6], size=4)

array([6, 1, 6, 3])

In [152]:
np.random.choice([1, 3, 6], p=[0.1, 0.8, 0.1], size=4)

array([3, 3, 1, 3])

In [153]:
A = np.random.randint(3, size=(5, 7))

In [154]:
np.save("my_data", A)

In [155]:
B = np.load("my_data.npy")

In [156]:
np.all(A == B)

True