# SD212: Graph Learning

# Sparse Matrices


In this lab, you will learn to use sparse matrices.


In [1]:
import numpy as np
from scipy import sparse

## CSR format


We first focus on the [CSR](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html) (Compressed Sparse Row) format. Note that there is the [CSC](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.html) (Compressed Sparse Column) format, which is nothing but the CSR format of the transpose matrix.


In [2]:
# random matrix (dense format)
X_dense = np.random.randint(3, size=(10, 5))

In [3]:
X_dense

array([[2, 1, 2, 2, 2],
       [0, 2, 1, 1, 1],
       [0, 2, 1, 2, 0],
       [2, 0, 1, 0, 0],
       [0, 0, 1, 2, 1],
       [2, 0, 0, 2, 1],
       [0, 2, 1, 0, 2],
       [0, 2, 2, 2, 0],
       [1, 2, 2, 1, 2],
       [2, 2, 0, 2, 1]])

In [4]:
X_csr = sparse.csr_matrix(X_dense)

In [5]:
X_csr.shape

(10, 5)

In [6]:
# number of non-zeros
X_csr.nnz

35

The data structure consists of 3 vectors:


In [7]:
X_csr.indices

array([0, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 0, 2, 2, 3, 4, 0, 3, 4, 1, 2,
       4, 1, 2, 3, 0, 1, 2, 3, 4, 0, 1, 3, 4])

In [8]:
X_csr.indptr

array([ 0,  5,  9, 12, 14, 17, 20, 23, 26, 31, 35])

In [9]:
X_csr.data

array([2, 1, 2, 2, 2, 2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 1,
       2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1])

## To do


- Can you find the number of non-zeros from these 3 vectors?
- What about the shape of the matrix?


## Arithmetic


Usual arithmetic operations apply to sparse matrices. The only contraint is to have the sparse matrix on the left-hand side of the operator.


In [10]:
n_row, n_col = 10, 4
X_dense = np.random.randint(2, size=(n_row, n_col))
X = sparse.csr_matrix(X_dense)

In [11]:
X_dense

array([[0, 1, 1, 1],
       [0, 0, 1, 1],
       [1, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 1, 1],
       [1, 0, 1, 0],
       [1, 1, 0, 1],
       [1, 1, 0, 1]])

In [12]:
a = np.ones(n_col, dtype=int)

In [13]:
b = X.dot(a)

In [14]:
b

array([3, 2, 3, 2, 1, 1, 3, 2, 3, 3], dtype=int32)

In [15]:
a = np.ones(n_row, dtype=int)
b = X.T.dot(a)

In [16]:
b

array([5, 6, 5, 7], dtype=int32)

In [17]:
A = np.random.randint(2, size=(n_col, 2))
B = X.dot(A)

In [18]:
A

array([[1, 0],
       [1, 1],
       [1, 1],
       [1, 0]])

In [19]:
B

array([[3, 2],
       [2, 1],
       [3, 1],
       [2, 1],
       [1, 1],
       [1, 0],
       [3, 2],
       [2, 1],
       [3, 1],
       [3, 1]], dtype=int32)

In [20]:
A = sparse.csr_matrix(A)
B = X.dot(A)

In [21]:
B

<10x2 sparse matrix of type '<class 'numpy.intc'>'
	with 19 stored elements in Compressed Sparse Row format>

In [22]:
B.toarray()

array([[3, 2],
       [2, 1],
       [3, 1],
       [2, 1],
       [1, 1],
       [1, 0],
       [3, 2],
       [2, 1],
       [3, 1],
       [3, 1]], dtype=int32)

In [23]:
X.T.dot(X)

<4x4 sparse matrix of type '<class 'numpy.intc'>'
	with 16 stored elements in Compressed Sparse Column format>

In [24]:
X.dot(X.T)

<10x10 sparse matrix of type '<class 'numpy.intc'>'
	with 88 stored elements in Compressed Sparse Row format>

In [25]:
n_row, n_col = 10, 5
X_dense = np.random.randint(3, size=(n_row, n_col))
X = sparse.csr_matrix(X_dense)

In [26]:
X

<10x5 sparse matrix of type '<class 'numpy.int32'>'
	with 38 stored elements in Compressed Sparse Row format>

In [27]:
Y = X > 1

In [28]:
Y

<10x5 sparse matrix of type '<class 'numpy.bool_'>'
	with 18 stored elements in Compressed Sparse Row format>

In [29]:
Y.dot(np.ones(n_col, dtype=int))

array([2, 4, 0, 2, 4, 2, 1, 1, 1, 1], dtype=int32)

In [30]:
Y.dot(np.ones(n_col, dtype=bool))

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True])

In [31]:
Z = 2 * X + 5 * Y

In [32]:
Z

<10x5 sparse matrix of type '<class 'numpy.intc'>'
	with 38 stored elements in Compressed Sparse Row format>

In [33]:
Z.power(2)

<10x5 sparse matrix of type '<class 'numpy.intc'>'
	with 38 stored elements in Compressed Sparse Row format>

## To do

Consider the following matrix:


In [34]:
n_row, n_col = 20, 4
X = sparse.csr_matrix(np.random.randint(3, size=(n_row, n_col)))

- Compute the vector of the Euclidean norm of each row.


In [35]:
norms = np.sqrt(np.sum(X.power(2), axis=1))

norms

matrix([[2.23606798],
        [2.64575131],
        [1.41421356],
        [1.73205081],
        [3.16227766],
        [2.44948974],
        [2.64575131],
        [3.16227766],
        [2.44948974],
        [1.41421356],
        [3.        ],
        [2.        ],
        [1.73205081],
        [3.16227766],
        [3.        ],
        [1.        ],
        [2.23606798],
        [2.23606798],
        [3.        ],
        [2.44948974]])

## Slicing


Sparse matrices can be sliced like numpy arrays.


In [36]:
n_row, n_col = 10, 5
X_dense = np.random.randint(3, size=(n_row, n_col))

In [37]:
X = sparse.csr_matrix(X_dense)

In [38]:
indices = [2, 5, 6]

In [39]:
X[indices]

<3x5 sparse matrix of type '<class 'numpy.int32'>'
	with 11 stored elements in Compressed Sparse Row format>

In [40]:
X[:, [1, 3]]

<10x2 sparse matrix of type '<class 'numpy.int32'>'
	with 15 stored elements in Compressed Sparse Row format>

## To do

Consider the following matrix:


In [41]:
n_row, n_col = 20, 10
X = sparse.csr_matrix(np.random.randint(3, size=(n_row, n_col)))

- Select the 5 rows of largest sums and build the corresponding CSR matrix (size 5 x 10).


In [42]:
n_largest = 5

indices = np.argsort(X.dot(np.ones(n_col)))[-n_largest:]
X_largest = X[indices]

X_largest

<5x10 sparse matrix of type '<class 'numpy.int32'>'
	with 45 stored elements in Compressed Sparse Row format>

## DIAG format


In [43]:
D = sparse.diags(np.arange(10))

In [44]:
D

<10x10 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements (1 diagonals) in DIAgonal format>

In [45]:
D.data

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [46]:
D.nnz

10

In [47]:
D = sparse.csr_matrix(D)

In [48]:
D.data

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [49]:
D.nnz

9

In [50]:
n_row, n_col = 10, 4
X = sparse.csr_matrix(np.random.randint(2, size=(n_row, n_col)))

In [51]:
D.dot(X)

<10x4 sparse matrix of type '<class 'numpy.float64'>'
	with 13 stored elements in Compressed Sparse Row format>

In [52]:
D = sparse.diags(np.ones(4))

In [53]:
X.dot(D)

<10x4 sparse matrix of type '<class 'numpy.float64'>'
	with 17 stored elements in Compressed Sparse Row format>

## To do


Consider the following matrix:


In [54]:
n_row, n_col = 20, 4
X = sparse.csr_matrix(np.random.randint(2, size=(n_row, n_col)))

Using sparse diagonal matrices:

- Normalize this matrix so that each row sums to 1 (or to 0 if the whole row is zero).


In [55]:
X.data = X.data.astype(float)

row_sums = np.array(X.sum(axis=1), dtype=float).ravel()

for i in range(n_row):
    if row_sums[i] != 0:
        X.data[X.indptr[i] : X.indptr[i + 1]] /= row_sums[i]

X.data

array([0.5       , 0.5       , 0.5       , 0.5       , 1.        ,
       0.33333333, 0.33333333, 0.33333333, 1.        , 0.5       ,
       0.5       , 0.5       , 0.5       , 1.        , 0.5       ,
       0.5       , 0.33333333, 0.33333333, 0.33333333, 1.        ,
       0.33333333, 0.33333333, 0.33333333, 0.5       , 0.5       ,
       1.        , 0.33333333, 0.33333333, 0.33333333, 1.        ,
       0.33333333, 0.33333333, 0.33333333])

## COO format


Another way to represent sparse matrices is the COO (COOrdinate) format. It is useful to load a matrix from a list of entries.


In [56]:
row = [1, 4, 2]
col = [2, 0, 2]
data = [1, 2, 3]

In [57]:
X_coo = sparse.coo_matrix((data, (row, col)), shape=(5, 5))

In [58]:
X_coo

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 3 stored elements in COOrdinate format>

In [59]:
X_coo.row

array([1, 4, 2])

In [60]:
X_coo.col

array([2, 0, 2])

In [61]:
X_coo.data

array([1, 2, 3])

You can change the format:


In [62]:
X_csr = X_coo.tocsr()

In [63]:
X_csr

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 3 stored elements in Compressed Sparse Row format>

In [64]:
X_csr.indices

array([2, 2, 0])

In [65]:
X_csr.indptr

array([0, 0, 1, 2, 2, 3])

In [66]:
X_csr.data

array([1, 3, 2])

In [67]:
X_csr.tocoo()

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 3 stored elements in COOrdinate format>

You can directly load a CSR matrix from COO format:


In [68]:
X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))

In [69]:
X_csr

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 3 stored elements in Compressed Sparse Row format>

Duplicate entries are not summed by default in the COO format (also in the CSR format in the last version of Scipy):


In [70]:
row = [1, 4, 2, 1]
col = [2, 0, 2, 2]
data = [1, 2, 3, 4]

In [71]:
X_coo = sparse.coo_matrix((data, (row, col)), shape=(5, 5))

In [72]:
X_coo

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 4 stored elements in COOrdinate format>

In [73]:
X_coo.nnz

4

In [74]:
X_coo.toarray()

array([[0, 0, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0]])

In [75]:
X_coo.dot(np.ones(5, dtype=int))

array([0, 5, 3, 0, 2], dtype=int32)

In [76]:
X_coo.data

array([1, 2, 3, 4])

In [77]:
X_coo.sum_duplicates()

In [78]:
X_coo

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 3 stored elements in COOrdinate format>

In [79]:
X_coo.data

array([5, 3, 2])

If data contain some zeros, these are coded as non-zeros by default:


In [80]:
row = [1, 4, 2]
col = [2, 0, 2]
data = [1, 2, 0]

In [81]:
X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))

In [82]:
X_csr

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 3 stored elements in Compressed Sparse Row format>

In [83]:
X_csr.eliminate_zeros()

In [84]:
X_csr

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 2 stored elements in Compressed Sparse Row format>

## To do

Consider the following matrix:


In [85]:
row = [1, 1, 2, 4, 2, 1]
col = [2, 2, 2, 0, 2, 2]
data = [1, 2, 3, 4, 0, 2]

X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))
X_csr.sum_duplicates()

- What is the number of non-zeros?
- Check your answer using `nnz`.


In [86]:
X_csr.nnz

3